name: Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Lint Python
        run: |
          isort . --diff --verbose
          black . --check --verbose
          flake8 . --verbose
      - name: Run server
        run: python manage.py runserver 8080 &
      - name: Install Node dependencies
        run: cd tasks && npm install
      - name: Run the tests
        run: node ./tasks/test.mjs || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://pypi.org/legacy/
